=== This-Is-Alex/FoodStart-SENG202/resources/exported_test_files/menu.dtd
<!-- DTD for representing menu -->
<!-- FOREIGN KEYS: item_id, recipe_id-->
<!ELEMENT menus (menu*)>
<!ELEMENT menu (menu_id, title, description, items)>
<!ELEMENT menu_id (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT items (item*)>
        <!ELEMENT item (default_id, item_id, name, item_description, recipes)>
<!ELEMENT recipes (recipe_id*)>
<!-- If is_prepared is true, recipe_id should be defined-->
        <!ELEMENT default_id (#PCDATA)>
<!ELEMENT item_id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT item_description (#PCDATA)>
<!ELEMENT recipe_id (#PCDATA)>

=== This-Is-Alex/FoodStart-SENG202/resources/data/TestMenu2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE menus SYSTEM "../dtd/menu.dtd">
<menus>
	<menu>
		<menu_id>1</menu_id>
		<title>Test title 2</title>
		<description>Test description</description>
		<items>
			<item>
				<item_id>0</item_id>
				<name>Boring Burger</name>
				<item_description>Test burger</item_description>
				<recipes>
					<recipe_id>1000</recipe_id>
					<recipe_id>1001</recipe_id>
				</recipes>
			</item>
		</items>
	</menu>
	<menu>
		<menu_id>2</menu_id>
		<title>Test title 3</title>
		<description>Test description</description>
		<items>
			<item>
				<item_id>0</item_id>
				<name>Boring Burger</name>
				<item_description>Test burger</item_description>
				<recipes>
					<recipe_id>1000</recipe_id>
					<recipe_id>1001</recipe_id>
				</recipes>
			</item>
		</items>
	</menu>
</menus>
