=== This-Is-Alex/FoodStart-SENG202/resources/exported_test_files/supplier.dtd
<!-- DTD for representing suppliers -->
<!ELEMENT suppliers (supplier*)>
<!ELEMENT supplier (sid, name, address, phone, email?, url?)>
<!ELEMENT sid (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone type (mobile|work|home) #REQUIRED>
<!ELEMENT email (#PCDATA)>
<!ELEMENT url (#PCDATA)>

=== This-Is-Alex/FoodStart-SENG202/resources/exported_test_files/SupplierExportTestEmpty.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE suppliers SYSTEM "supplier.dtd">
<suppliers>
    <supplier>
        <sid>4</sid>
        <name/>
        <address/>
        <phone type="home"/>
    </supplier>
    <supplier>
        <sid>0</sid>
        <name/>
        <address/>
        <phone type="home"/>
    </supplier>
    <supplier>
        <sid>5</sid>
        <name/>
        <address/>
        <phone type="home"/>
    </supplier>
    <supplier>
        <sid>2</sid>
        <name/>
        <address/>
        <phone type="mobile"/>
    </supplier>
    <supplier>
        <sid>1</sid>
        <name/>
        <address/>
        <phone type="work"/>
    </supplier>
    <supplier>
        <sid>3</sid>
        <name/>
        <address/>
        <phone type="home"/>
    </supplier>
</suppliers>
