=== This-Is-Alex/FoodStart-SENG202/resources/dtd/ingredient.dtd
<!-- DTD for representing ingredients -->
<!-- (C) Neville Churcher 2019 -->
<!-- FOREIGN KEYS: None-->
<!ENTITY version "V0.01 (C) Neville Churcher 2019">
<!ELEMENT ingredients (ingredient*)>
<!ELEMENT ingredient (id, name, truck_stock, kitchen_stock, dietary)>
<!ATTLIST ingredient unit (ml|g|count) #REQUIRED>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT truck_stock (#PCDATA)>
<!ELEMENT kitchen_stock (#PCDATA)>
<!-- List of dietary requirements -->
<!ELEMENT dietary (vegan?, vegetarian?, nut_free?, egg_free?, gluten_free?, dairy_free?)>
<!ELEMENT vegan (#PCDATA)>
<!ELEMENT vegetarian (#PCDATA)>
<!ELEMENT nut_free (#PCDATA)>
<!ELEMENT egg_free (#PCDATA)>
<!ELEMENT gluten_free (#PCDATA)>
<!ELEMENT dairy_free (#PCDATA)>
<!-- End list of dietary requirements -->

=== This-Is-Alex/FoodStart-SENG202/resources/data/TestIngredients1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ingredients SYSTEM "../dtd/ingredient.dtd">
<ingredients>
	<ingredient unit="g">
		<id>0</id>
		<name>Edam Cheese</name>
		<truck_stock>1000</truck_stock>
		<kitchen_stock>2000</kitchen_stock>
		<dietary>
			<vegan>true</vegan>
			<vegetarian>true</vegetarian>
			<nut_free>true</nut_free>
			<gluten_free>true</gluten_free>
			<dairy_free>true</dairy_free>
		</dietary>
	</ingredient>
</ingredients>

=== This-Is-Alex/FoodStart-SENG202/resources/data/TestIngredients3.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ingredients SYSTEM "../dtd/ingredient.dtd">
<ingredients>
	<ingredient unit="g">
		<id>2</id>
		<name>TestItem2</name>
		<truck_stock>1</truck_stock>
		<kitchen_stock>1</kitchen_stock>
		<dietary>
			<vegan>true</vegan>
			<vegetarian>true</vegetarian>
			<nut_free>true</nut_free>
			<gluten_free>true</gluten_free>
			<dairy_free>true</dairy_free>
		</dietary>
	</ingredient>
	<ingredient unit="ml">
		<id>3</id>
		<name>TestItem3</name>
		<truck_stock>1</truck_stock>
		<kitchen_stock>1</kitchen_stock>
		<dietary>
			<vegan>true</vegan>
			<vegetarian>true</vegetarian>
			<nut_free>true</nut_free>
			<gluten_free>true</gluten_free>
			<dairy_free>true</dairy_free>
		</dietary>
	</ingredient>
	<ingredient unit="count">
		<id>4</id>
		<name>TestItem4</name>
		<truck_stock>1</truck_stock>
		<kitchen_stock>1</kitchen_stock>
		<dietary>
			<vegan>true</vegan>
			<vegetarian>true</vegetarian>
			<nut_free>true</nut_free>
			<gluten_free>true</gluten_free>
			<dairy_free>true</dairy_free>
		</dietary>
	</ingredient>
</ingredients>

=== This-Is-Alex/FoodStart-SENG202/resources/data/TestIngredients5.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ingredients SYSTEM "../dtd/ingredient.dtd">
<ingredients>
	<ingredient unit="g">
		<id>8</id>
		<name>TestItem8</name>
		<truck_stock>1</truck_stock>
		<kitchen_stock>1</kitchen_stock>
		<dietary>
			<vegan>true</vegan>
			<vegetarian>true</vegetarian>
			<nut_free>true</nut_free>
			<gluten_free>true</gluten_free>
			<dairy_free>true</dairy_free>
		</dietary>
	</ingredient>
	<ingredient unit="g">
		<id>9</id>
		<name>TestItem9</name>
		<truck_stock>1</truck_stock>
		<kitchen_stock>1</kitchen_stock>
		<dietary>
			<vegan>false</vegan>
			<vegetarian>false</vegetarian>
			<nut_free>false</nut_free>
			<gluten_free>false</gluten_free>
			<dairy_free>false</dairy_free>
		</dietary>
	</ingredient>
	<ingredient unit="g">
		<id>10</id>
		<name>TestItem10</name>
		<truck_stock>1</truck_stock>
		<kitchen_stock>1</kitchen_stock>
		<dietary>
			
		</dietary>
	</ingredient>
	<ingredient unit="g">
		<id>11</id>
		<name>TestItem11</name>
		<truck_stock>1</truck_stock>
		<kitchen_stock>1</kitchen_stock>
		<dietary>
			<vegan>false</vegan>
			<vegetarian>true</vegetarian>
			<gluten_free>false</gluten_free>
			<dairy_free>true</dairy_free>
		</dietary>
	</ingredient>
</ingredients>

=== This-Is-Alex/FoodStart-SENG202/resources/data/Ingredients.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE ingredients SYSTEM "../dtd/ingredient.dtd">
<ingredients>
	<ingredient unit="g">
		<id>0</id>
		<name>Edam Cheese</name>
		<truck_stock>1580</truck_stock>
		<kitchen_stock>5500</kitchen_stock>
		<dietary>
			<vegetarian>true</vegetarian>
			<nut_free>true</nut_free>
		</dietary>
	</ingredient>
	<ingredient unit="count">
		<id>1</id>
		<name>Hamburger Bun</name>
		<truck_stock>45</truck_stock>
		<kitchen_stock>256</kitchen_stock>
		<dietary>
			<vegan>true</vegan>
			<vegetarian>true</vegetarian>
			<nut_free>true</nut_free>
		</dietary>
	</ingredient>
</ingredients>
