=== This-Is-Alex/FoodStart-SENG202/resources/dtd/menu.dtd
<!-- DTD for representing menu -->
<!-- FOREIGN KEYS: item_id, recipe_id-->
<!ELEMENT menu (menu_id, title, description, (item*))>
<!ELEMENT menu_id (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT item (item_id, name, item_description, recipes)>
<!ELEMENT recipes (recipe_id*)>
<!-- If is_prepared is true, recipe_id should be defined-->
<!ELEMENT item_id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT item_description (name)>
<!ELEMENT recipe_id (#PCDATA)>

=== This-Is-Alex/FoodStart-SENG202/resources/data/SampleMenu.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE menu SYSTEM "../dtd/menu.dtd">
<menu>
	<menu_id>0</menu_id>
	<title>Default Menu</title>
	<description>Normal menu when nothing special is on</description>
	<items>
		<item>
            <default_id>0</default_id>
			<item_id>0</item_id>
			<name>Boring Burger</name>
			<item_description>A burger so boring it's just some cheese in a bun</item_description>
			<recipes>
				<recipe_id>0</recipe_id>
				<recipe_id>1</recipe_id>
			</recipes>
		</item>
	</items>
</menu>
