=== This-Is-Alex/FoodStart-SENG202/resources/dtd/recipes.dtd
<!-- DTD for representing recipes -->
<!-- FOREIGN KEYS: ingredient_id-->
<!ELEMENT recipes (recipe*)>
<!ELEMENT recipe (recipe_id, name, ingredients, method)>
<!ELEMENT recipe_id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT ingredients (ingredient+)>
<!ELEMENT ingredient (ingredient_id, quantity)>
<!ELEMENT ingredient_id (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT method (step+)>
<!ELEMENT step (#PCDATA)>

=== This-Is-Alex/FoodStart-SENG202/resources/data/Recipes.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE recipes SYSTEM "../dtd/recipes.dtd">
<recipes>
	<recipe>
		<recipe_id>0</recipe_id>
		<name>Small cheese burger</name>
		<ingredients>
			<ingredient>
				<ingredient_id>1</ingredient_id>
				<quantity>1</quantity>
			</ingredient>
			<ingredient>
				<ingredient_id>0</ingredient_id>
				<quantity>50</quantity>
			</ingredient>
		</ingredients>
		<method>Put the cheese between the buns and serve it</method>
		<price>4.5</price>
	</recipe>
	<recipe>
		<recipe_id>0</recipe_id>
		<name>Large cheese burger</name>
		<ingredients>
			<ingredient>
				<ingredient_id>1</ingredient_id>
				<quantity>1</quantity>
			</ingredient>
			<ingredient>
				<ingredient_id>0</ingredient_id>
				<quantity>150</quantity>
			</ingredient>
		</ingredients>
		<method>Put the cheese between the buns and serve it</method>
		<price>6</price>
	</recipe>
</recipes>

=== This-Is-Alex/FoodStart-SENG202/resources/data/TestBadRecipes2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE recipes SYSTEM "../dtd/recipes.dtd">
<recipes>
	<recipe>
		<recipe_id>1234</recipe_id>
		<name>Pickle burger</name>
		<ingredients>
			<ingredient>
				<ingredient_id>8999</ingredient_id>
				<quantity>2</quantity>
			</ingredient>
			<ingredient>
				<ingredient_id>9001</ingredient_id>
				<quantity>1</quantity>
			</ingredient>
		</ingredients>
		<method>Put the pickle in the bun and serve it</method>
		<price>2.5</price>
	</recipe>
	<recipe>
		<recipe_id>1235</recipe_id>
		<name>Just a Pickle</name>
		<ingredients>
			<ingredient>
				<ingredient_id>9000</ingredient_id>
				<quantity>1</quantity>
			</ingredient>
		</ingredients>
		<method>Yum, pickles</method>
		<price>1</price>
	</recipe>
</recipes>
