=== This-Is-Alex/FoodStart-SENG202/resources/data/sales_log_xml_files/sales_log.dtd
<!-- DTD for representing sales log -->
<!-- FOREIGN KEYS: recipe_id, ingredient_id-->
<!ELEMENT sales (sale*)>
<!ELEMENT sale (id, name, date, cost, payment, recipes)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT cost (#PCDATA)>
<!ELEMENT payment (#PCDATA)>
<!ELEMENT recipes (recipe+)>
<!ELEMENT recipe (recipe_id, ingredients?, quantity)>
<!ELEMENT recipe_id (#PCDATA)>
<!ELEMENT ingredients (ingredient+, otf_price)>
<!ELEMENT ingredient (ingredient_id, ingredient_quantity)>
<!ELEMENT ingredient_id (#PCDATA)>
<!ELEMENT ingredient_quantity (#PCDATA)>
<!ELEMENT otf_price (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>

=== This-Is-Alex/FoodStart-SENG202/resources/data/sales_log_xml_files/SalesLogParserTestDataNonIntegerID.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sales SYSTEM "sales_log.dtd" >
<sales>
	<sale>
		<id>not an integer</id>
		<name>Jom</name>
		<date>668512349</date>
		<cost>15.50</cost>
		<payment>cash</payment>
		<recipes>
			<recipe>
				<recipe_id>1</recipe_id>
				<quantity>3</quantity>
			</recipe>
			<recipe>
				<recipe_id>2</recipe_id>
				<ingredients>
					<ingredient>
						<ingredient_id>1</ingredient_id>
						<ingredient_quantity>3</ingredient_quantity>
					</ingredient>
					<ingredient>
						<ingredient_id>2</ingredient_id>
						<ingredient_quantity>2</ingredient_quantity>
					</ingredient>
					<otf_price>7.50</otf_price>
				</ingredients>
				<quantity>2</quantity>
			</recipe>
			<recipe>
				<recipe_id>3</recipe_id>
				<quantity>2</quantity>
			</recipe>
		</recipes>
	</sale></sales>

=== This-Is-Alex/FoodStart-SENG202/resources/data/sales_log_xml_files/SalesLogParserTestDataBadForeignKeys.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sales SYSTEM "sales_log.dtd" >
<sales>
	<sale>
		<id>1</id>
		<name>blo</name>
		<date>329185442</date>
		<cost>15.69</cost>
		<payment>eftpos</payment>
		<recipes>
			<recipe>
				<recipe_id>-123124</recipe_id>
				<quantity>1</quantity>
			</recipe>
		</recipes>
	</sale></sales>
